### ISSUE TITLE
Compile sqlite against GNU readline when available.

### ISSUE THREAD

**Issue by richardkmichael** [richardkmichael/homebrew-core#1]
Needs GNU readline installed; note, it is keg-only.

From the SQLite documentation (`configure.ac`):

```
#-------------------------------------------------------------------------
# Two options to enable readline compatible libraries: 
#
#   --enable-editline
#   --enable-readline
#
# Both are enabled by default. If, after command line processing both are
# still enabled, the script searches for editline first and automatically
# disables readline if it is found. So, to use readline explicitly, the
# user must pass "--disable-editline". To disable command line editing
# support altogether, "--disable-editline --disable-readline".
```

SQLite's `./configure` has helpful options:

```
  --enable-editline       enable BSD editline support
  --disable-readline      disable readline support

  --with-readline-lib     specify readline library
  --with-readline-inc     specify readline include paths
```

Hence, Homebrew should invoke:

`./configure --disable-editline --enable-readline --with-readline-lib=$(brew --prefix readline)/lib --with-readline-inc=$(brew --prefix readline)/include`

Try testing with:  `brew install --interactive sqlite`, then in the spawned shell:

```
export PATH=/usr/local/bin/${PATH} # Provide brew the command substitution sub-shell.

./configure --disable-editline --enable-readline --with-readline-lib=$(brew --prefix readline)/lib --with-readline-inc=$(brew --prefix readline)/include
```

Unfortunately, `./configure` complains, hmm.. sqlite bug?

`configure: WARNING: unrecognized options: --with-readline-lib, --with-readline-inc`

Use CPPFLAGS and LDFLAGS instead:

```
LDFLAGS=-L/usr/local/opt/readline/lib CPPFLAGS=-I/usr/local/opt/readline/include ./configure --disable-editline --enable-readline && make

# ...time passes

otool -L ./sqlite3
./sqlite3:
        /usr/local/opt/readline/lib/libreadline.7.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

- [x] How to do this with ruby in the sqlite formula?
- [ ] Output helpful message to homebrew user regarding compilation against`libedit` vs `readline` and their respective `rc` files.

### Reference

BSD editline http://thrysoee.dk/editline/
  * How close is `.editrc` to `.inputrc`

**Comment by richardkmichael** [comment]
Using `refute foo.empty?` in a homebrew test causes:

```shell
$ brew test sqlite3
Testing sqlite
==> Using the sandbox
==> otool -L /usr/local/Cellar/sqlite/3.16.1/bin/sqlite3
        /usr/local/opt/readline/lib/libreadline.7.dylib (compatibility version 7.0.0, current version 7.0.0)
Error: sqlite: failed
test returned false
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

... while `assert foo.any?` works [and fails the test] correctly.

**Comment by richardkmichael** [comment]
Need to test build when `readline` is not installed.
